name: Publish to npm

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: write # Required to push changes to the repository
  id-token: write # Required for authentication with npm registry

jobs:
  pub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.8.0
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
